---
deployment:
  tasks:
    - export DEPLOYPATH=/home/bazaarco/public_html/
    - /bin/cp index.js $DEPLOYPATH
    - /bin/cp pages/api $DEPLOYPATH 
    - /bin/cp -R components $DEPLOYPATH
    - /bin/cp -R models $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH 
    - /bin/cp -R styles.css $DEPLOYPATH
    - /bin/cp -R utils $DEPLOYPATH
    - /bin/cp next.config.js $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp postcss.config.js $DEPLOYPATH
    - /bin/cp tailwind.config.js $DEPLOYPATH